define

var countCalendarRows = { COUNTROWS ( 'd Calendar' ) }

var totalActualCost = { ROUND(SUM('f Actual Cost'[Cost]),0) }

VAR tests=
UNION (
    ROW (
        "TestName", "Count Calendar Rows",
        "ExpectedValue", 4322,
        "ActualValue", countCalendarRows
    ),
    ROW (
        "TestName", "Total Actual Cost",
        "ExpectedValue", 345658461,
        "ActualValue", totalActualCost
    )
)

EVALUATE ADDCOLUMNS(tests, "Passed", [ExpectedValue] = [ActualValue])
